### ISSUE TITLE
Error 403 when opening

### ISSUE THREAD

**Issue by mortalux** [fmmmlee/GW2-Addon-Manager#212] opened 2023-05-21 02:48 UTC
### Please attach a copy of config.yaml or config.ini to the issue.
[](url)
**Describe the bug**
When trying to fix Archdps, accidently made the route for update to bin64 and since then it crashed my addon manager and wont let it open again saying the access is denied.

**To Reproduce**
Select bin64 as route for downloading addons -> select new addons to download -> press update -> close the app and reopen.

**Additional context**
This happenned whilst trying to find a way to update and reset my addon manager and archdps.

**don't forget to attach the config file to the issue**
[log.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/11523636/log.txt)

**Comment by Friendly0Fire** [comment] 2023-05-21 04:10
Do as the error message says: wait and try again later. Nothing we can do about it, it's been covered to death already.

Duplicate of #156 #125 #208 #195 #192 and probably more.

**Closed as not planned by Friendly0Fire** 2023-05-21 04:10 UTC
Labels: bug
