### ISSUE TITLE
Disabling add-ons that aren't installed crashes the updater

### ISSUE THREAD

**Issue by MarineShadow** [fmmmlee/GW2-Addon-Manager#4] opened 2019-09-01 09:08 UTC
If you select an add-on that wasn't installed, and press the Disable button, after confirming the action, the updater throws an "An unhandled exception occurred." can't find the file \Guild Wars 2\bin64\d912pxy.dll for example

**Comment by fmmmlee** [comment] 2019-09-01 16:32
Working on a fix, should be out in a few hours

**Comment by fmmmlee** [comment] 2019-09-01 19:24
Released a new update; after downloading it and restarting the program, see if the issue persists. 

Interestingly, the text that says whether an add-on is installed or not is based on reading a section of the configuration file that's _also_ supposed to be checked when handling the disable button, so if it doesn't say "installed" then it shouldn't be trying to move any files around....regardless, I added a quick file existence check that should prevent the problem for now; I'll keep an eye out when editing for where this issue might have sprung from. Sorry for the late response!

**Comment by MarineShadow** [comment] 2019-09-02 08:41
Yep, it disables them now instead of crashing :)
The next issue is re-enabling them... still getting the same crash.
Issue only exists when I've never installed an addon.

I can only re-enable an addon like this as follows:
Using the delete button on an addon that's never been installed/downloaded, it does something, and I can re-enable the addon again.

[config.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/3565113/config.txt)

**Comment by fmmmlee** [comment] 2019-09-02 08:46
Odd. It sounds like somehow the "installed" field got set somehow when they're not installed, so the application looks for files that aren't there ("delete" goes through and deletes the files if they exists and clears the relevant properties in that field, which would explain why it helps). I'll probably end up writing a verification function that just compares the actual folder to the configuration file and corrects any discrepancies and put it in places it would be useful. Interestingly, I haven't been able to reproduce the issue at all on my end (disabling and enabling add-ons that are not installed seems to work for me). I'll see if I can make a proper, conclusive fix tomorrow. Is this issue with just one or two particular add-ons or all of them?

**Comment by fmmmlee** [comment] 2019-09-02 08:50
Also, if you feel up to the hassle, you could try deleting config.ini and resetting your bin64 folder back to defaults by deleting it and then launching + closing the game, and then seeing if the issue persists. It might work. I work tomorrow (and am fast approaching sleep right now) but hopefully I'll be able to dig up the root issue that started the problem.

**Comment by fmmmlee** [comment] 2019-10-09 03:21
Tested on latest dev build and problem seems to be resolved. If after next release (1.0) the problem persists, feel free to reopen this issue.

**Closed by fmmmlee** 2019-10-09 03:21 UTC
