### ISSUE TITLE
Github Rate Limit prevents start

### ISSUE THREAD

**Issue by belst** [fmmmlee/GW2-Addon-Manager#44] opened 2020-08-03 10:37 UTC
**Describe the bug**
The Program doesnt start after you get a Github error. Probably rate limit reached.

**To Reproduce**
Restart the program a few times and select a few addons until you reach the rate limit

**Comment by fmmmlee** [comment] 2020-08-06 22:22
Duplicate of #20

**Closed by fmmmlee** 2020-08-06 22:22 UTC
Labels: bug
