### ISSUE TITLE
Button above "Finish" to go back to start page.

### ISSUE THREAD

**Issue by TybaIt** [fmmmlee/GW2-Addon-Manager#32] opened 2020-05-27 23:13 UTC
Add a button above "Finish" to go back to the start page. just noticed that when you update some and want to do more, like disabling some addons for new patch. you can just click on Finish, closing the program and having to restart it again.

**Comment by fmmmlee** [comment] 2020-07-08 22:03
duplicate of #36 , implemented in #39

**Closed by fmmmlee** 2020-07-08 22:03 UTC
Labels: enhancement
