### ISSUE TITLE
Access denied to config.xml after 1.3.0 update

### ISSUE THREAD

**Issue by sicu** [fmmmlee/GW2-Addon-Manager#77] opened 2020-11-07 16:16 UTC
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
Clicked update to 1.3.0 in the app, it finished downloading and nothing more happened the next 5 minutes. 
So I closed and re-launched it and got an error (I forget what it was). I then deleted my files and manually added them from the latest release on github. I now get the following error:
![gw2adnmngr_err](https://user-images.githubusercontent.com/26230029/98445770-d6687100-2119-11eb-81b1-6599f54b803e.png)
No idea why it wants to put the config file at the root of c:\, but it adds it there if I start as admin. Might have something to do with where my app folder is located. `C:\#custom\GW2\GW2-AddonManager`
It now works fine as long as I run as admin, but that's not really ok. Where do I tell the app to store the config file?

**Additional context**
Was working fine before the update.

**don't forget to attach the config file to the issue**
[config.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/5505043/config.zip)

**Comment by Draeggiar** [comment] 2020-11-07 18:07
I was able to reproduce it, attaching stack trace here:
[log.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/5505243/log.txt)

Not sure how it worked before, but problem is with your path - it cannot contain `#` symbol. Althoug it is not illegal chacarter in windows path, special characters may cause problems, so I do not recomend using them. 

As to fixing it:
Replacing `#` char with `%23` fixes the issue, but I dont know if it is a clean solution. There will be other problematic symbols, that will need replacing e.g. `@`should we find and replace them all somehow ? Or maybe config should be stored in one of system folder such as`%appdata%`? The game itself actually does that.

**Comment by fmmmlee** [comment] 2020-11-07 18:07
Hm. I would initially think that it could be an issue with path construction given the # character in your app folder path, but if it works when running as admin that probably isn't it. 

Are there any special permissions assigned to your game folder or other directories in that path? I've heard in the past of some users having admin permissions attached to their program files folders and perhaps a similar issue is present here.

**Comment by fmmmlee** [comment] 2020-11-07 18:08
Never mind on my last comment - if @Draeggiar was able to reproduce it given the # character then that must be the issue; I'll see how to go about taking care of this in one way or another. Thanks Draeggiar for hunting this one down!

**Comment by Draeggiar** [comment] 2020-11-08 09:43
Something felt wrong so i double checked the stack trace, and turns out it was only part of the problem. Somehow folder `Resources\Addons` was missing and that caused the exception.

**Comment by sicu** [comment] 2020-11-09 13:38
I changed the naming scheme of my folders, but thanks for digging into this 👍

**Closed** 2020-11-09 19:11 UTC
Labels: bug
