### ISSUE TITLE
DXGI.dll already exists and the updater crashes.

### ISSUE THREAD

**Issue by Void2258** [fmmmlee/GW2-Addon-Manager#209] opened 2023-04-27 00:07 UTC
**Describe the bug**
Receive an error about a file already existing and the manager crashes on every run. Removing the file lets that run complete but it just comes back the next time.

**To Reproduce**
Run update
get error message
Crash

**Additional context**
![image](https://user-images.githubusercontent.com/6126362/234727597-8741471d-2d1c-4a39-b78e-c79fd740ce6d.png)

Don't know what config file is being referred to. I tried to attach the one in the GW2 add ons folder but they type is not allowed.

**Comment by Zyian** [comment] 2023-04-27 00:19
Please ensure that you are running the latest version of the addon manager available here: https://github.com/gw2-addon-loader/GW2-Addon-Manager/releases/tag/v1.4.5

The issue you're describing has been addressed

**Comment by Zyian** [comment] 2023-04-27 00:20
This has also been discussed here: https://github.com/gw2-addon-loader/GW2-Addon-Manager/issues/203

**Comment by Zyian** [comment] 2023-05-03 16:03
Duplicate of #203

**Closed as not planned by Zyian** 2023-05-03 16:03 UTC
Labels: bug
